import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>macOS Web</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles.menubar}>
        <div className={styles.menus}>
          {['', 'File', 'Window', 'Help'].map((menu, i) => (
            <div key={i}>{menu}</div>
          ))}
        </div>
        <div>12:00 PM</div>
      </div>

      <div className={styles.desktop}>
        <h1 className={styles.title}>
          Welcome to <strong>macOS web</strong>!
        </h1>
      </div>

      <div className={styles.dock} />
    </div>
  )
}
